version: '3'
services:
  website:
    image: nginx:latest
    container_name: website
    volumes:
      - /home/kuol/services/LootTable/src:/usr/share/nginx/html
    ports:
    - "8080:80"
    restart: always